name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_WIDGETS_TOKEN }}
          base: header, activity, community, repositories, metadata
          commits_authoring: Konstantin Sebrovskiy, SEBROVATER, sebrovskiy.k@gmail.com
          repositories_affiliations: owner, collaborator, organization_member
          base_indepth: yes

      - name: Used languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_WIDGETS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_ignored: markdown, c
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_sections: most-used
          commits_authoring: Konstantin Sebrovskiy, SEBROVATER, sebrovskiy.k@gmail.com
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 60
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_categories: data, markup, programming, prose

      - name: Profile and detailed game history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: ${{ secrets.STEAM_ID }}
          plugin_steam_sections: player, recently-played
          plugin_steam_games_ignored: 570, 216250
          plugin_steam_games_limit: 7
          plugin_steam_recent_games_limit: 7
          plugin_steam_achievements_limit: 0
          plugin_steam_playtime_threshold: 0.5
